repos:
  - repo: https://github.com/pycqa/flake8
    rev: ''
    hooks:
      - id: flake8
        exclude: migrations,settings.py,venv,.venv
        args: ["--max-line-length=120", "--ignore=E402,E501,W503"]