services:
  web:
    build: .
    command: python manage.py runserver
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"

#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"
#
#  celery:
#    build: .
#    command: celery -A currency_exchange worker -l info
#    env_file:
#      - .env
#    volumes:
#      - .:/code
#    depends_on:
#      - db
#      - redis
#
#  celery-beat:
#    build: .
#    command: celery -A currency_exchange beat -l info
#    env_file:
#      - .env
#    volumes:
#      - .:/code
#    depends_on:
#      - db
#      - redis