services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    environment:
      - PRE_COMMIT_HOME=/tmp/pre-commit-cache
      - IS_DOCKER=TRUE
    depends_on:
      - db
      - redis
    restart: unless-stopped
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  redis-commander:
    image: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379

#  celery:
#    build: .
#    command: celery -A CurrencyExchange worker -l info
#    env_file:
#      - .env
#    volumes:
#      - .:/code
#    depends_on:
#      - db
#      - redis
#
#  celery-beat:
#    build: .
#    command: celery -A CurrencyExchange beat -l info
#    env_file:
#      - .env
#    volumes:
#      - .:/code
#    depends_on:
#      - db
#      - redis