services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
  #
  #  celery:
  #    build: .
  #    command: celery -A currency_exchange worker -l info
  #    env_file:
  #      - .env
  #    volumes:
  #      - .:/code
  #    depends_on:
  #      - db
  #      - redis
  #
  #  celery-beat:
  #    build: .
  #    command: celery -A currency_exchange beat -l info
  #    env_file:
  #      - .env
  #    volumes:
  #      - .:/code
  #    depends_on:
  #      - db
  #      - redis