# Generated by Django 5.2 on 2025-04-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite_currencies',
            field=models.ManyToManyField(blank=True, to='currencies.currency'),
        ),
    ]
