# Generated by Django 5.2 on 2025-04-04 11:30

from django.db import migrations


def load_initial_currencies(apps, schema_editor):
    currencies = apps.get_model('currencies', 'Currency')

    initial_currencies = [
        {'base': 'USD', 'name': 'US Dollar', 'symbol': '$'},
        {'base': 'EUR', 'name': 'Euro', 'symbol': '€'},
        {'base': 'GBP', 'name': 'British Pound', 'symbol': '£'},
        {'base': 'JPY', 'name': 'Japanese Yen', 'symbol': '¥'},
        {'base': 'AUD', 'name': 'Australian Dollar', 'symbol': 'A$'},
        {'base': 'CAD', 'name': 'Canadian Dollar', 'symbol': 'C$'},
        {'base': 'CHF', 'name': 'Swiss Franc', 'symbol': 'CHF'},
        {'base': 'CNY', 'name': 'Chinese Yuan', 'symbol': '¥'},
        {'base': 'SEK', 'name': 'Swedish Krona', 'symbol': 'kr'},
        {'base': 'NZD', 'name': 'New Zealand Dollar', 'symbol': 'NZ$'},
    ]

    for currency in initial_currencies:
        currencies.objects.get_or_create(**currency)


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_currencies),
    ]
