
from django.db import migrations


def load_initial_currencies(apps, schema_editor):
    currencies = apps.get_model('currencies', 'Currency')

    initial_currencies = [
        {'base': 'USD', 'name': 'US Dollar', 'symbol': '$'},
        {'base': 'EUR', 'name': 'Euro', 'symbol': '€'},
        {'base': 'GBP', 'name': 'British Pound', 'symbol': '£'},
        {'base': 'JPY', 'name': 'Japanese Yen', 'symbol': '¥'},
        {'base': 'AUD', 'name': 'Australian Dollar', 'symbol': 'A$'},
        {'base': 'CAD', 'name': 'Canadian Dollar', 'symbol': 'C$'},
        {'base': 'CHF', 'name': 'Swiss Franc', 'symbol': 'CHF'},
        {'base': 'CNY', 'name': 'Chinese Yuan', 'symbol': '¥'},
        {'base': 'SEK', 'name': 'Swedish Krona', 'symbol': 'kr'},
        {'base': 'NZD', 'name': 'New Zealand Dollar', 'symbol': 'NZ$'},
        {'base': 'AED', 'name': 'United Arab Emirates Dirham', 'symbol': 'د.إ'},
        {'base': 'AFN', 'name': 'Afghan Afghani', 'symbol': '؋'},
        {'base': 'ALL', 'name': 'Albanian Lek', 'symbol': 'L'},
        {'base': 'AMD', 'name': 'Armenian Dram', 'symbol': '֏'},
        {'base': 'ANG', 'name': 'Netherlands Antillean Guilder', 'symbol': 'ƒ'},
        {'base': 'AOA', 'name': 'Angolan Kwanza', 'symbol': 'Kz'},
        {'base': 'ARS', 'name': 'Argentine Peso', 'symbol': '$'},
        {'base': 'AWG', 'name': 'Aruban Florin', 'symbol': 'ƒ'},
        {'base': 'AZN', 'name': 'Azerbaijani Manat', 'symbol': '₼'},
        {'base': 'BAM', 'name': 'Bosnia-Herzegovina Convertible Mark', 'symbol': 'KM'},
        {'base': 'BBD', 'name': 'Barbadian Dollar', 'symbol': '$'},
        {'base': 'BDT', 'name': 'Bangladeshi Taka', 'symbol': '৳'},
        {'base': 'BGN', 'name': 'Bulgarian Lev', 'symbol': 'лв'},
        {'base': 'BHD', 'name': 'Bahraini Dinar', 'symbol': '.د.ب'},
        {'base': 'BIF', 'name': 'Burundian Franc', 'symbol': 'FBu'},
        {'base': 'BMD', 'name': 'Bermudian Dollar', 'symbol': '$'},
        {'base': 'BND', 'name': 'Brunei Dollar', 'symbol': '$'},
        {'base': 'BOB', 'name': 'Bolivian Boliviano', 'symbol': 'Bs'},
        {'base': 'BRL', 'name': 'Brazilian Real', 'symbol': 'R$'},
        {'base': 'BSD', 'name': 'Bahamian Dollar', 'symbol': '$'},
        {'base': 'BTN', 'name': 'Bhutanese Ngultrum', 'symbol': 'Nu.'},
        {'base': 'BWP', 'name': 'Botswanan Pula', 'symbol': 'P'},
        {'base': 'BYN', 'name': 'Belarusian Ruble', 'symbol': 'Br'},
        {'base': 'BZD', 'name': 'Belize Dollar', 'symbol': '$'},
        {'base': 'CDF', 'name': 'Congolese Franc', 'symbol': 'FC'},
        {'base': 'CLP', 'name': 'Chilean Peso', 'symbol': '$'},
        {'base': 'COP', 'name': 'Colombian Peso', 'symbol': '$'},
        {'base': 'CRC', 'name': 'Costa Rican Colón', 'symbol': '₡'},
        {'base': 'CUP', 'name': 'Cuban Peso', 'symbol': '$'},
        {'base': 'CVE', 'name': 'Cape Verdean Escudo', 'symbol': '$'},
        {'base': 'CZK', 'name': 'Czech Koruna', 'symbol': 'Kč'},
        {'base': 'DJF', 'name': 'Djiboutian Franc', 'symbol': 'Fdj'},
        {'base': 'DKK', 'name': 'Danish Krone', 'symbol': 'kr'},
        {'base': 'DOP', 'name': 'Dominican Peso', 'symbol': '$'},
        {'base': 'DZD', 'name': 'Algerian Dinar', 'symbol': 'د.ج'},
        {'base': 'EGP', 'name': 'Egyptian Pound', 'symbol': '£'},
        {'base': 'ERN', 'name': 'Eritrean Nakfa', 'symbol': 'Nfk'},
        {'base': 'ETB', 'name': 'Ethiopian Birr', 'symbol': 'Br'},
        {'base': 'FJD', 'name': 'Fijian Dollar', 'symbol': '$'},
        {'base': 'FKP', 'name': 'Falkland Islands Pound', 'symbol': '£'},
        {'base': 'FOK', 'name': 'Faroese Króna', 'symbol': 'kr'},
        {'base': 'GEL', 'name': 'Georgian Lari', 'symbol': '₾'},
        {'base': 'GGP', 'name': 'Guernsey Pound', 'symbol': '£'},
        {'base': 'GHS', 'name': 'Ghanaian Cedi', 'symbol': '₵'},
        {'base': 'GIP', 'name': 'Gibraltar Pound', 'symbol': '£'},
        {'base': 'GMD', 'name': 'Gambian Dalasi', 'symbol': 'D'},
        {'base': 'GNF', 'name': 'Guinean Franc', 'symbol': 'FG'},
        {'base': 'GTQ', 'name': 'Guatemalan Quetzal', 'symbol': 'Q'},
        {'base': 'GYD', 'name': 'Guyanese Dollar', 'symbol': '$'},
        {'base': 'HKD', 'name': 'Hong Kong Dollar', 'symbol': '$'},
        {'base': 'HNL', 'name': 'Honduran Lempira', 'symbol': 'L'},
        {'base': 'HRK', 'name': 'Croatian Kuna', 'symbol': 'kn'},
        {'base': 'HTG', 'name': 'Haitian Gourde', 'symbol': 'G'},
        {'base': 'HUF', 'name': 'Hungarian Forint', 'symbol': 'Ft'},
        {'base': 'IDR', 'name': 'Indonesian Rupiah', 'symbol': 'Rp'},
        {'base': 'ILS', 'name': 'Israeli New Shekel', 'symbol': '₪'},
        {'base': 'IMP', 'name': 'Isle of Man Pound', 'symbol': '£'},
        {'base': 'INR', 'name': 'Indian Rupee', 'symbol': '₹'},
        {'base': 'IQD', 'name': 'Iraqi Dinar', 'symbol': 'ع.د'},
        {'base': 'IRR', 'name': 'Iranian Rial', 'symbol': '﷼'},
        {'base': 'ISK', 'name': 'Icelandic Króna', 'symbol': 'kr'},
        {'base': 'JEP', 'name': 'Jersey Pound', 'symbol': '£'},
        {'base': 'JMD', 'name': 'Jamaican Dollar', 'symbol': '$'},
        {'base': 'JOD', 'name': 'Jordanian Dinar', 'symbol': 'د.ا'},
        {'base': 'KES', 'name': 'Kenyan Shilling', 'symbol': 'Sh'},
        {'base': 'KGS', 'name': 'Kyrgyzstani Som', 'symbol': 'с'},
        {'base': 'KHR', 'name': 'Cambodian Riel', 'symbol': '៛'},
        {'base': 'KID', 'name': 'Kiribati Dollar', 'symbol': '$'},
        {'base': 'KMF', 'name': 'Comorian Franc', 'symbol': 'CF'},
        {'base': 'KRW', 'name': 'South Korean Won', 'symbol': '₩'},
        {'base': 'KWD', 'name': 'Kuwaiti Dinar', 'symbol': 'د.ك'},
        {'base': 'KYD', 'name': 'Cayman Islands Dollar', 'symbol': '$'},
        {'base': 'KZT', 'name': 'Kazakhstani Tenge', 'symbol': '₸'},
        {'base': 'LAK', 'name': 'Lao Kip', 'symbol': '₭'},
        {'base': 'LBP', 'name': 'Lebanese Pound', 'symbol': 'ل.ل'},
        {'base': 'LKR', 'name': 'Sri Lankan Rupee', 'symbol': 'Rs'},
        {'base': 'LRD', 'name': 'Liberian Dollar', 'symbol': '$'},
        {'base': 'LSL', 'name': 'Lesotho Loti', 'symbol': 'L'},
        {'base': 'LYD', 'name': 'Libyan Dinar', 'symbol': 'ل.د'},
        {'base': 'MAD', 'name': 'Moroccan Dirham', 'symbol': 'د.م.'},
        {'base': 'MDL', 'name': 'Moldovan Leu', 'symbol': 'L'},
        {'base': 'MGA', 'name': 'Malagasy Ariary', 'symbol': 'Ar'},
        {'base': 'MKD', 'name': 'Macedonian Denar', 'symbol': 'ден'},
        {'base': 'MMK', 'name': 'Myanmar Kyat', 'symbol': 'Ks'},
        {'base': 'MNT', 'name': 'Mongolian Tögrög', 'symbol': '₮'},
        {'base': 'MOP', 'name': 'Macanese Pataca', 'symbol': 'P'},
        {'base': 'MRU', 'name': 'Mauritanian Ouguiya', 'symbol': 'UM'},
        {'base': 'MUR', 'name': 'Mauritian Rupee', 'symbol': '₨'},
        {'base': 'MVR', 'name': 'Maldivian Rufiyaa', 'symbol': '.ރ'},
        {'base': 'MWK', 'name': 'Malawian Kwacha', 'symbol': 'MK'},
        {'base': 'MXN', 'name': 'Mexican Peso', 'symbol': '$'},
        {'base': 'MYR', 'name': 'Malaysian Ringgit', 'symbol': 'RM'},
        {'base': 'MZN', 'name': 'Mozambican Metical', 'symbol': 'MT'},
        {'base': 'NAD', 'name': 'Namibian Dollar', 'symbol': '$'},
        {'base': 'NGN', 'name': 'Nigerian Naira', 'symbol': '₦'},
        {'base': 'NIO', 'name': 'Nicaraguan Córdoba', 'symbol': 'C$'},
        {'base': 'NOK', 'name': 'Norwegian Krone', 'symbol': 'kr'},
        {'base': 'NPR', 'name': 'Nepalese Rupee', 'symbol': '₨'},
        {'base': 'OMR', 'name': 'Omani Rial', 'symbol': 'ر.ع.'},
        {'base': 'PAB', 'name': 'Panamanian Balboa', 'symbol': 'B/.'},
        {'base': 'PEN', 'name': 'Peruvian Sol', 'symbol': 'S/.'},
        {'base': 'PGK', 'name': 'Papua New Guinean Kina', 'symbol': 'K'},
        {'base': 'PHP', 'name': 'Philippine Peso', 'symbol': '₱'},
        {'base': 'PKR', 'name': 'Pakistani Rupee', 'symbol': '₨'},
        {'base': 'PLN', 'name': 'Polish Złoty', 'symbol': 'zł'},
        {'base': 'PYG', 'name': 'Paraguayan Guaraní', 'symbol': '₲'},
        {'base': 'QAR', 'name': 'Qatari Riyal', 'symbol': 'ر.ق'},
        {'base': 'RON', 'name': 'Romanian Leu', 'symbol': 'lei'},
        {'base': 'RSD', 'name': 'Serbian Dinar', 'symbol': 'дин'},
        {'base': 'RUB', 'name': 'Russian Ruble', 'symbol': '₽'},
        {'base': 'RWF', 'name': 'Rwandan Franc', 'symbol': 'FRw'},
        {'base': 'SAR', 'name': 'Saudi Riyal', 'symbol': 'ر.س'},
        {'base': 'SBD', 'name': 'Solomon Islands Dollar', 'symbol': '$'},
        {'base': 'SCR', 'name': 'Seychellois Rupee', 'symbol': '₨'},
        {'base': 'SDG', 'name': 'Sudanese Pound', 'symbol': 'ج.س.'},
        {'base': 'SGD', 'name': 'Singapore Dollar', 'symbol': '$'},
        {'base': 'SHP', 'name': 'Saint Helena Pound', 'symbol': '£'},
        {'base': 'SLE', 'name': 'Sierra Leonean Leone', 'symbol': 'Le'},
        {'base': 'SLL', 'name': 'Sierra Leonean Leone (old)', 'symbol': 'Le'},
        {'base': 'SOS', 'name': 'Somali Shilling', 'symbol': 'Sh'},
        {'base': 'SRD', 'name': 'Surinamese Dollar', 'symbol': '$'},
        {'base': 'SSP', 'name': 'South Sudanese Pound', 'symbol': '£'},
        {'base': 'STN', 'name': 'São Tomé and Príncipe Dobra', 'symbol': 'Db'},
        {'base': 'SYP', 'name': 'Syrian Pound', 'symbol': '£'},
        {'base': 'SZL', 'name': 'Swazi Lilangeni', 'symbol': 'L'},
        {'base': 'THB', 'name': 'Thai Baht', 'symbol': '฿'},
        {'base': 'TJS', 'name': 'Tajikistani Somoni', 'symbol': 'SM'},
        {'base': 'TMT', 'name': 'Turkmenistani Manat', 'symbol': 'T'},
        {'base': 'TND', 'name': 'Tunisian Dinar', 'symbol': 'د.ت'},
        {'base': 'TOP', 'name': 'Tongan Paʻanga', 'symbol': 'T$'},
        {'base': 'TRY', 'name': 'Turkish Lira', 'symbol': '₺'},
        {'base': 'TTD', 'name': 'Trinidad and Tobago Dollar', 'symbol': '$'},
        {'base': 'TVD', 'name': 'Tuvaluan Dollar', 'symbol': '$'},
        {'base': 'TWD', 'name': 'New Taiwan Dollar', 'symbol': 'NT$'},
        {'base': 'TZS', 'name': 'Tanzanian Shilling', 'symbol': 'Sh'},
        {'base': 'UAH', 'name': 'Ukrainian Hryvnia', 'symbol': '₴'},
        {'base': 'UGX', 'name': 'Ugandan Shilling', 'symbol': 'Sh'},
        {'base': 'UYU', 'name': 'Uruguayan Peso', 'symbol': '$'},
        {'base': 'UZS', 'name': 'Uzbekistani Som', 'symbol': 'soʻm'},
        {'base': 'VES', 'name': 'Venezuelan Bolívar', 'symbol': 'Bs.'},
        {'base': 'VND', 'name': 'Vietnamese Đồng', 'symbol': '₫'},
        {'base': 'VUV', 'name': 'Vanuatu Vatu', 'symbol': 'Vt'},
        {'base': 'WST', 'name': 'Samoan Tala', 'symbol': 'T'},
        {'base': 'XAF', 'name': 'Central African CFA Franc', 'symbol': 'FCFA'},
        {'base': 'XCD', 'name': 'East Caribbean Dollar', 'symbol': '$'},
        {'base': 'XCG', 'name': 'East Caribbean Gold', 'symbol': 'ECG'},
        {'base': 'XDR', 'name': 'Special Drawing Rights', 'symbol': 'SDR'},
        {'base': 'XOF', 'name': 'West African CFA Franc', 'symbol': 'CFA'},
        {'base': 'XPF', 'name': 'CFP Franc', 'symbol': '₣'},
        {'base': 'YER', 'name': 'Yemeni Rial', 'symbol': '﷼'},
        {'base': 'ZAR', 'name': 'South African Rand', 'symbol': 'R'},
        {'base': 'ZMW', 'name': 'Zambian Kwacha', 'symbol': 'ZK'},
        {'base': 'ZWL', 'name': 'Zimbabwean Dollar', 'symbol': '$'}
    ]

    for currency in initial_currencies:
        currencies.objects.update_or_create(base=currency['base'], defaults=currency)


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_load_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_currencies),
    ]
